### ISSUE TITLE
图标上传申请多久后会看到logo?在哪里查看进度呢？

### ISSUE THREAD

**Issue by Lena-Ho** [TP-Lab/tokens#3862]
按照官网的流程完成了币LOGO上传申请，请问多久会有进度？要在哪里关注进度呢？

**Comment by NewOriginToken** [comment]
同问

**Comment by ldzx2020** [comment]
500U 我可以在一天内上传完成代币信息，不完成不收费。欢迎滴滴！

**Comment by NewOriginToken** [comment]
之前3000TPT已经转了，
https://bscscan.com/tx/0x91ad4276ec3f757e0dd3fc8bca6ae853f29aad38b5fd8b60e8642bdaab2fa658

ldzx2020 ***@***.***> 于2021年11月2日周二 下午10:28写道：

**Comment by liuadmin123** [comment]
qq:320289549联系我

**Comment by hailang47923** [comment]
> 500U 我可以在一天内上传完成代币信息，不完成不收费。欢迎滴滴！



> 500U 我可以在一天内上传完成代币信息，不完成不收费。欢迎滴滴！

qq：1127737063，期待回复

**Comment by NewOriginToken** [comment]
已经更新好了

在 2021年11月12日星期五，hailang ***@***.***> 写道：

**Comment by shaboshi** [comment]
300U  2天通过

**Comment by ldzx2020** [comment]
300U  24小时上架。可以找我！



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月17日 13:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TP-Lab/tokens] 图标上传申请多久后会看到logo?在哪里查看进度呢？ (Issue #3862) |

300U 2天通过

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shaboshi** [comment]
看不到进度的
















在 2021-11-17 13:43:57，"ldzx2020" ***@***.***> 写道：

300U 24小时上架。可以找我！



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月17日 13:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TP-Lab/tokens] 图标上传申请多久后会看到logo?在哪里查看进度呢？ (Issue #3862) |

300U 2天通过

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ldzx2020** [comment]
什么？



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月17日 13:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TP-Lab/tokens] 图标上传申请多久后会看到logo?在哪里查看进度呢？ (Issue #3862) |

看不到进度的
















在 2021-11-17 13:43:57，"ldzx2020" ***@***.***> 写道：

300U 24小时上架。可以找我！



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月17日 13:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TP-Lab/tokens] 图标上传申请多久后会看到logo?在哪里查看进度呢？ (Issue #3862) |

300U 2天通过

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shaboshi** [comment]
你是要问什么，说清楚
















在 2021-11-17 13:49:33，"ldzx2020" ***@***.***> 写道：

什么？



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月17日 13:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TP-Lab/tokens] 图标上传申请多久后会看到logo?在哪里查看进度呢？ (Issue #3862) |

看不到进度的
















在 2021-11-17 13:43:57，"ldzx2020" ***@***.***> 写道：

300U 24小时上架。可以找我！



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月17日 13:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TP-Lab/tokens] 图标上传申请多久后会看到logo?在哪里查看进度呢？ (Issue #3862) |

300U 2天通过

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ldzx2020** [comment]
没事儿了！



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月17日 13:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TP-Lab/tokens] 图标上传申请多久后会看到logo?在哪里查看进度呢？ (Issue #3862) |

你是要问什么，说清楚
















在 2021-11-17 13:49:33，"ldzx2020" ***@***.***> 写道：

什么？



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月17日 13:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TP-Lab/tokens] 图标上传申请多久后会看到logo?在哪里查看进度呢？ (Issue #3862) |

看不到进度的
















在 2021-11-17 13:43:57，"ldzx2020" ***@***.***> 写道：

300U 24小时上架。可以找我！



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月17日 13:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TP-Lab/tokens] 图标上传申请多久后会看到logo?在哪里查看进度呢？ (Issue #3862) |

300U 2天通过

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shixin1198** [comment]
qq:17819700联系我

**Comment by ldzx2020** [comment]
QQ  3032648242

有偿代办TPl ogo  全链上架。全链代币发行！
