### ISSUE TITLE
Update contract address

### ISSUE THREAD

**Issue by MinecraftDAO** [TP-Lab/tokens#7272]
hi there,
We made a request #7194 earlier and it has been merged, However, we found that the previously submitted token contract address is not final but used for intermediate testing.
The wrong contract address submitted before is: 0xf00f513078A8Dcc91b2Cfd3A7e0892613556feAf
The correct token contract address is: 0x52dEF1CBc8d8476d45637222BEf2B71Ac8fB4FCa
Could you please help to transfer the logo and information to the correct contract address? Thanks.
BTW, although the wrong request was merged, the wrong token did not display the logo in TP.

**Comment by MinecraftDAO** [comment]
We found that the wrong token shows the logo, it should be because the cache has not been refreshed before, but we do not use this test token, please help to transfer the logo and information to the correct contract, thank you very much

**Comment by opera0001** [comment]
![image](https://user-images.githubusercontent.com/99245006/170812887-f098b7af-deac-47c6-8cad-5a801e8a34a0.png)
First of all, the logo must be updated and can be searched and viewed normally.
The new TPT hash value needs to be submitted when changing the contract address or a new logo, because this problem is not caused by our audit, and it took a long time to feed back this problem. Therefore, it is necessary to resubmit the application.

**Comment by MinecraftDAO** [comment]
ok got it, i will resubmit the logo,thx

**Comment by MinecraftDAO** [comment]
already resubmit in request #7288 , Thx
