### ISSUE TITLE
Add NATHHL logo and info #9670 feedback

### ISSUE THREAD

**Issue by msxiaoliu** [TP-Lab/tokens#9695]
sorry to bother you，I have already provided the donation information, but it is still rejected. I don’t know where the problem lies. This is the first time I try to submit the token information independently. Please give me your guidance. I will base it on your opinion submit，thank you！

The following is the information I submitted according to other people's ideas,
5000TPT：https://bscscan.com/tx/0xfe735274b6ea0d6d0f2601df8d52a1a37b71858b930d6c7605f3af86e4d81f6f
https://bscscan.com/tx/0xc765b3581de9a862b593ce205a9dd6c12fafc8082c268e9a1ee9e969abb15741

**Comment by opera0001** [comment]
The processing is already completed for you. In the previous order, you did not provide the TPT donation hash value, which is why it did not pass.

**Comment by msxiaoliu** [comment]
OK, thank you, it has been submitted now, right?

**Comment by msxiaoliu** [comment]
> The processing is already completed for you. In the previous order, you did not provide the TPT donation hash value, which is why it did not pass.

thank you very much

**Comment by zsf11221** [comment]
sorry to bother you，I have already provided the donation information, but it is still rejected. I don’t know where the problem lies. This is the first time I try to submit the token information independently. Please give me your guidance. I will base it on your opinion submit，thank you！
https://bscscan.com/tx/0xbc16575d0434a2c45a55c5bfc464359a2a8b68146960c4b6f22c46501dd651b8
