### ISSUE TITLE
If my contract involves calling an external contract for dividends, such as lp nft dividends, can I post an avatar?

### ISSUE THREAD

**Issue by dragonkingserv** [TP-Lab/tokens#9802]

**Comment by dragonkingserv** [comment]
@opera0001

**Comment by opera0001** [comment]
Yes, dear, if its use is normal and essential, there should be no issue, and you can proceed with the application as usual. Of course, we hope that the functionality you describe aligns with the actual functionality because if any risky issues are discovered with the token, we may remove the token's logo and apply a risk warning to the token.
